const { test } = require("@playwright/test");
const { LoginPage } = require ("../pages/loginPage")

test.describe("Negative tests for Login flow", async () => {
    test("C200 - P1:Authorization with empty fields", async ({ page }) => {
        const login = new LoginPage(page);
        await login.goToLogin()
        await login.clickOnLoginButton()
        await login.logInPopUpIsDisplayed()
        await login.clickOnSignInButton()
        await login.verifyErrorMessageEmailInputEmpty()
        await login.verifyErrorMessageEmailInputEmpty()
    });
    test("C200 - P2:Authorization with empty password field", async ({ page }) => {
        const login = new LoginPage(page);
        await login.goToLogin()
        await login.clickOnLoginButton()
        await login.logInPopUpIsDisplayed()
        await login.enterValidEmail()
        await login.clickOnSignInButton()
        await login.verifyErrorMessagePasswordInputEmpty()
    });
    test("C200 - P3:Authorization with empty email field", async ({ page }) => {
        const login = new LoginPage(page);
        await login.goToLogin()
        await login.clickOnLoginButton()
        await login.logInPopUpIsDisplayed()
        await login.enterValidPassword()
        await login.clickOnSignInButton()
        await login.verifyErrorMessageEmailInputEmpty()
    });
    test("C203 - P1:Authorization with invalid credentials email", async ({ page }) => {
        const login = new LoginPage(page);
        await login.goToLogin()
        await login.clickOnLoginButton()
        await login.logInPopUpIsDisplayed()
        await login.enterValidPassword()
        await login.enterInvalidEmailOrPhone('testuser rentzila@gmail.com')
        await login.clickOnSignInButton()
        await login.verifyErrorMessageEmailInputInvalid()
        await login.clearEmailInput()
        await login.enterInvalidEmailOrPhone('еуіегіуккутеяшдф')
        await login.clickOnSignInButton()
        await login.verifyErrorMessageEmailInputInvalid()
        await login.clearEmailInput()
        await login.enterInvalidEmailOrPhone('testuserrentzilagmail .com')
        await login.clickOnSignInButton()
        await login.verifyErrorMessageEmailInputInvalid()
        await login.clearEmailInput()
        await login.enterInvalidEmailOrPhone('testuserrentzila@gmailcom')
        await login.clickOnSignInButton()
        await login.verifyErrorMessageEmailInputInvalid()
        await login.clearEmailInput()
        await login.enterInvalidEmailOrPhone('testuserrentzila@gmail')
        await login.clickOnSignInButton()
        await login.verifyErrorMessageEmailInputInvalid()
        await login.clearEmailInput()
        await login.enterInvalidEmailOrPhone('testuserrentzila@.com')
        await login.clickOnSignInButton()
        await login.verifyErrorMessageEmailInputInvalid()
        await login.clearEmailInput()
        await login.enterInvalidEmailOrPhone('testuserrentzila')
        await login.clickOnSignInButton()
        await login.verifyErrorMessageEmailInputInvalid()
        await login.clearEmailInput()
        await login.enterInvalidEmailOrPhone('testuserrentzila@@gmail.com')
        await login.clickOnSignInButton()
        await login.verifyErrorMessageEmailInputInvalid()
    });
    test("C203 - P2:Authorization with invalid credentials password", async ({ page }) => {
        const login = new LoginPage(page);
        await login.goToLogin()
        await login.clickOnLoginButton()
        await login.logInPopUpIsDisplayed()
        await login.enterValidEmail()
        await login.enterInvalidPassword('Testuser10 ')
        await login.clickOnSignInButton()
        await login.verifyErrorMessagePasswordInputInvalid()
        await login.clearPasswordInput()
        await login.enterInvalidPassword(' Testuser10')
        await login.clickOnSignInButton()
        await login.verifyErrorMessagePasswordInputInvalid()
        await login.clearPasswordInput()
        await login.enterInvalidPassword('testuser10')
        await login.clickOnSignInButton()
        await login.verifyErrorMessagePasswordInputInvalid()
        await login.clearPasswordInput()
        await login.enterInvalidPassword('TESTUSER10')
        await login.clickOnSignInButton()
        await login.verifyErrorMessagePasswordInputInvalid()
        await login.clearPasswordInput()
        await login.enterInvalidPassword('Еуіегіук10')
        await login.clickOnSignInButton()
        await login.verifyErrorMessagePasswordInputInvalid()
        await login.clearPasswordInput()
        await login.enterInvalidPassword('Testuser13')
        await login.clickOnSignInButton()
        await login.verifyErrorMessageEmailOrPasswordInvalid()
    });
    test("C207 - Authorization with invalid phone", async ({ page }) => {
        const login = new LoginPage(page);
        await login.goToLogin()
        await login.clickOnLoginButton()
        await login.logInPopUpIsDisplayed()
        await login.enterValidPassword()
        await login.enterInvalidEmailOrPhone('506743060')
        await login.clickOnSignInButton()
        await login.verifyErrorMessageEmailInputInvalid()
        await login .clearEmailInput()
        await login.enterInvalidEmailOrPhone('050674306')
        await login.clickOnSignInButton()
        await login.verifyErrorMessageEmailInputInvalid()
        await login .clearEmailInput()
        await login.enterInvalidEmailOrPhone('+380-50-674-3060')
        await login.clickOnSignInButton()
        await login.verifyErrorMessageEmailInputInvalid()
        await login .clearEmailInput()
        await login.enterInvalidEmailOrPhone('+380 50 674 3060')
        await login.clickOnSignInButton()
        await login.verifyErrorMessageEmailInputInvalid()
        await login .clearEmailInput()
        await login.enterInvalidEmailOrPhone('+380(50)6743060')
        await login.clickOnSignInButton()
        await login.verifyErrorMessageEmailInputInvalid()
        await login .clearEmailInput()
        await login.enterInvalidEmailOrPhone('(50)6743060')
        await login.clickOnSignInButton()
        await login.verifyErrorMessageEmailInputInvalid()
        await login .clearEmailInput()
        await login.enterInvalidEmailOrPhone('05067430600')
        await login.clickOnSignInButton()
        await login.verifyErrorMessageEmailInputInvalid()
        await login .clearEmailInput()
        await login.enterInvalidEmailOrPhone('+10506743060')
        await login.clickOnSignInButton()
        await login.verifyErrorMessageEmailInputInvalid()
        await login .clearEmailInput()
        await login.enterInvalidEmailOrPhone('+0506743060')
        await login.clickOnSignInButton()
        await login.verifyErrorMessageEmailInputInvalid()
    });
    test("C199 - Reset the password with invalid email", async ({ page }) => {
        const login = new LoginPage(page);
        await login.goToLogin()
        await login.clickOnLoginButton()
        await login.logInPopUpIsDisplayed()
        await login.clickOnForgotPasswordButton()
        await login.verifyforgotPasswordPopUp()
        await login.clickOnSubmitButtonForgotPasswordPopUp()
        await login.verifyEmailInputForgotPasswordPopUpEmpty()
        await login.enterEmailOrPhoneForgotPasswordPopUp('testuserrentzila@gmail.com')
        await login.clickOnXbuttonForgotPasswordPopUp()
        await login.clickOnForgotPasswordButton()
        await login.verifyforgotPasswordPopUp()
        await login.enterEmailOrPhoneForgotPasswordPopUp('testuser rentzila@gmail.com')
        await login.clickOnSubmitButtonForgotPasswordPopUp()
        await login.verifyEmailInputForgotPasswordPopUpInvalid()
        await login.clearEmailOrPhoneForgotPasswordPopUp()
        await login.enterEmailOrPhoneForgotPasswordPopUp('еуіегіуккутеяшдф')
        await login.clickOnSubmitButtonForgotPasswordPopUp()
        await login.verifyEmailInputForgotPasswordPopUpInvalid()
        await login.clearEmailOrPhoneForgotPasswordPopUp()
        await login.enterEmailOrPhoneForgotPasswordPopUp('testuserrentzilagmail.com')
        await login.clickOnSubmitButtonForgotPasswordPopUp()
        await login.verifyEmailInputForgotPasswordPopUpInvalid()
        await login.clearEmailOrPhoneForgotPasswordPopUp()
        await login.enterEmailOrPhoneForgotPasswordPopUp('testuserrentzila@gmailcom')
        await login.clickOnSubmitButtonForgotPasswordPopUp()
        await login.verifyEmailInputForgotPasswordPopUpInvalid()
        await login.clearEmailOrPhoneForgotPasswordPopUp()
        await login.enterEmailOrPhoneForgotPasswordPopUp('testuserrentzila@gmail')
        await login.clickOnSubmitButtonForgotPasswordPopUp()
        await login.verifyEmailInputForgotPasswordPopUpInvalid()
        await login.clearEmailOrPhoneForgotPasswordPopUp()
        await login.enterEmailOrPhoneForgotPasswordPopUp('testuserrentzila@.com')
        await login.clickOnSubmitButtonForgotPasswordPopUp()
        await login.verifyEmailInputForgotPasswordPopUpInvalid()
        await login.clearEmailOrPhoneForgotPasswordPopUp()
        await login.enterEmailOrPhoneForgotPasswordPopUp('testuserrentzila')
        await login.clickOnSubmitButtonForgotPasswordPopUp()
        await login.verifyEmailInputForgotPasswordPopUpInvalid()
        await login.clearEmailOrPhoneForgotPasswordPopUp()
        await login.enterEmailOrPhoneForgotPasswordPopUp('testuserrentzila@@gmail.com')
        await login.clickOnSubmitButtonForgotPasswordPopUp()
        await login.verifyEmailInputForgotPasswordPopUpInvalid()
        await login.clearEmailOrPhoneForgotPasswordPopUp()
        await login.enterEmailOrPhoneForgotPasswordPopUp(' testuserrentzila@gmail.com')
        await login.clickOnSubmitButtonForgotPasswordPopUp()
        await login.verifyEmailInputForgotPasswordPopUpInvalid()
        await login.clearEmailOrPhoneForgotPasswordPopUp()
        await login.enterEmailOrPhoneForgotPasswordPopUp('testuserrentzila@gmail.com ')
        await login.clickOnSubmitButtonForgotPasswordPopUp()
        await login.verifyEmailInputForgotPasswordPopUpInvalid()
        await login.clearEmailOrPhoneForgotPasswordPopUp()
        await login.enterEmailOrPhoneForgotPasswordPopUp('testuserrentzila99@gmail.com')
        await login.clickOnSubmitButtonForgotPasswordPopUp()
        await login.verifyMainErrorMessageForgotPasswordPopUpInvalid()
    });
});
test.describe("Positive tests for Login flow", async () => {
    test("C201 - Authorization with valid email and password", async ({ page }) => {
        const login = new LoginPage(page);
        await login.goToLogin()
        await login.clickOnLoginButton()
        await login.logInPopUpIsDisplayed()
        await login.enterValidEmail1()
        await login.enterValidPassword1()
        await login.clickOnPasswordEye()
        await login.clickOnSignInButton()
        await login.clickOnNavbarBlockButton()
        await login.verifyEmailAccount('testuserrentzila@gmail.com')
        await login.clickOnLogOutButton()
        await login.clickOnLoginButton()
        await login.logInPopUpIsDisplayed()
        await login.enterValidEmail2()
        await login.enterValidPassword1()
        await login.clickOnPasswordEye()
        await login.clickOnSignInButton()
        await login.clickOnNavbarBlockButton()
        await login.verifyEmailAccount('testuserrentzila@gmail.com')
        await login.clickOnLogOutButton()
    });
});

